name: bnk-dataexport
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib
  - osmnx>=2
  - tqdm
  - geojson

  - jupyter
  - jupyterlab
  - ipywidgets
  - ipykernel

  - pytest
  - contextily
  - pyrosm
  - pip:
    # not available via conda-forge:
    - opencv-python
    - pre-commit
    - python-slugify
    - growbikenet