name: bnk-dataexport
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib
  - osmnx>=2
  - tqdm
  - geojson

  - growbikenet
  - pyrosm>=0.11
  - jupyterlab
  - pre-commit
  - pip:
    - python-slugify